#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=18:00:00
#PBS -N roitracking
#PBS -V

set -e

if [ ! -f wm_anat.nii.gz ]; then
    [ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
    echo $FREESURFER_LICENSE > license.txt
    echo "creating masks"    
    export SINGULARITYENV_FREESURFER_LICENSE=`pwd`/license.txt
    time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 ./create_wm_mask.sh
fi

mkdir -p roi
roiCount=$(ls roi/*.mif | wc -l)
chkVal=0
if [ $roiCount -eq $chkVal ]; then
    echo "generate rois"

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/bsc_GenROIfromPairStringList_BL
fi

echo "tracking"
time singularity exec -e docker://brainlife/mrtrix_on_mcr:1.0 ./trackROI2ROI.sh

echo "generating tracts/"
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/wma_formatForBrainLife

echo "generating surfaces/"
time singularity exec -e docker://brainlife/docker-pythonvtk ./freesurfer2vtks.py aparc+aseg.nii.gz

