#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=14:00:00
#PBS -N ensembletracking
#PBS -V

module load singularity 2> /dev/null

echo "creating masks"
time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./create_wm_mask.sh"

echo "roi generation"
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./ROI/roiGeneration

echo "tracking"
time singularity exec -e docker://brainlife/mrtrix_on_mcr:1.0 ./trackROI2ROI.sh

#if [ -s track.tck ]
#then
#    exit 0
#else
#	echo "ensemble tracking missing"
#	exit 1
#fi
